baseURL = 'https://inphobia.github.io/'
languageCode = 'en-us'
title = 'a collection of technical notes'
theme = 'hugo-book'
capitalizeListTitles = false
disablePathToLower = false
disableKinds = 'taxonomy'
pluralizeListTitles = false
enableGitInfo = true
titlecasestyle = "none"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableofcontents]
    startlevel = 2
    endlevel = 4

[outputs]
  home     = ["html"]
  page     = ["html"]
  section  = ["html"]
  term     = ["html"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[imaging]
  [imaging.exif]
    disableDate = true
    disableLatLong = true
    excludeFields = '.*'

[params]
  BookSection = 'docs'
  BookTheme = 'auto'
  BookSearch = false
  BookComments = false
  BookFavicon = "favicon.svg"
  BookLastChangeLink = 'https://github.com/inphobia/inphobia.github.io/commit/{{ .GitInfo.Hash }}'

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleanalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.x]
    disable = true
  [privacy.youtube]
    disable = true
