baseURL = 'https://inphobia.github.io/'
languageCode = 'en-us'
title = 'a collection of technical notes'
theme = 'hugo-book'

[menu]
  [[menu.home]]
    name = "about"
    url = "/about/"
    weight = 2

[markup.tableOfContents]
  startLevel = 1

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  BookTheme = 'dark'
  BookSearch = false
  BookComments = false
  BookSection = '/'
