baseURL = 'https://inphobia.github.io/'
languageCode = 'en-us'
title = 'a collection of technical notes'
theme = 'hugo-book'
capitalizeListTitles = false
disablePathToLower = false
disableKinds = 'taxonomy'
pluralizeListTitles = false

[markup.tableOfContents]
  startLevel = 1

[outputs]
  home     = ["html"]
  page     = ["html"]
  section  = ["html"]
  term     = ["html"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  BookTheme = 'dark'
  BookSearch = false
  BookComments = false
