baseURL = 'https://inphobia.github.io/'
languageCode = 'en-us'
title = 'a collection of technical notes'
theme = 'hugo-book'
capitalizeListTitles = false
disablePathToLower = false
disableKinds = 'taxonomy'
pluralizeListTitles = false
enableGitInfo = true
titlecasestyle = "none"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableofcontents]
    startlevel = 2
    endlevel = 4

[outputs]
  home     = ["html"]
  page     = ["html"]
  section  = ["html"]
  term     = ["html"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  BookTheme = 'dark'
  BookSearch = false
  BookComments = false
  BookLastChangeLink = 'https://github.com/inphobia/inphobia.github.io/commit/{{ .GitInfo.Hash }}'
